apiVersion: apps/v1
kind: Deployment
metadata:
  name: kops 
  labels:
    app: kops:v1
spec:
  selector:
    matchLabels:
        app: kops
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kops
    spec:
      containers:
        - name: kops
          image: 748209023631.dkr.ecr.us-east-1.amazonaws.com/kops:v1
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: Always
